-- 006_billing_fees.sql
-- Adds fee columns to payout_invoices and makes created_by nullable
-- (bills are now auto-generated by the system, not by a merchant user action).
--
-- Fee model:
--   subscription_fee_cusd  fixed $20/month platform fee
--   service_fee_cusd       2% of gross_cusd (GMV)
--   net_cusd               gross_cusd - subscription_fee_cusd - service_fee_cusd
--                          (the amount AkibaMiles will pay out to the merchant)

ALTER TABLE payout_invoices
  ALTER COLUMN created_by DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS subscription_fee_cusd numeric(12,2) NOT NULL DEFAULT 20.00,
  ADD COLUMN IF NOT EXISTS service_fee_cusd       numeric(12,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS net_cusd               numeric(12,2) NOT NULL DEFAULT 0.00;
